{% set name = "asyncssh" %}
{% set version = "1.16.1" %}
{% set sha256 = "51c29b1858dfb0a42734dc984744d890df444c97becb602ce6809c2a1423f31e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ronf/asyncssh/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py < 34]
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - cryptography

test:
  imports:
    - asyncssh

about:
  home: https://github.com/ronf/asyncssh
  license: EPL-1.0
  summary: "AsyncSSH: Asynchronous SSHv2 client and server library"

extra:
  recipe-maintainers:
    - vamega
