{% set name = "asyncssh" %}
{% set version = "2.19.0" %}
{% set sha256 = "723dead4d068b558708dc66a4ca7e7a93a813aa9416036eccb9af4c03ae2cf30" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - cryptography >=39.0
    - pyopenssl >=23.0.0
    - python-gssapi >=1.2.0
    - typing_extensions >=4.0.0

test:
  imports:
    - asyncssh
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ronf/asyncssh
  license: EPL-1.0
  summary: 'AsyncSSH: Asynchronous SSHv2 client and server library'

extra:
  recipe-maintainers:
    - apmorton
    - vamega
