{% set name = "asyncssh" %}
{% set version = "2.9.0" %}
{% set sha256 = "3cc337d806619465455bf187e8a91e3f575423718184e238f9ae8c41c4f33af1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.4
    - setuptools
    - pip
  run:
    - python >=3.4
    - cryptography
    - pyopenssl >=17.0.0
    - python-gssapi >=1.2.0

test:
  imports:
    - asyncssh

about:
  home: https://github.com/ronf/asyncssh
  license: EPL-1.0
  summary: 'AsyncSSH: Asynchronous SSHv2 client and server library'

extra:
  recipe-maintainers:
    - vamega
