appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: O9+zy3O3jMzeZqIfRmQjgwjlvqSDrYwabbZIZFwtK4+uWY5Q1rC1GhfTgUqyLVDtgfJdUuyKRmSQUCsv1bFmCDqMqOia/oI9C1Ft6K/uqsyyZp54WPl/EwSyR+nABcltB6mayDUm0DQ2TqLq0D5zls3LW9osBBrkcrK3BJgqlzAcYIe4gHAN66tWdcBsGLOhW3Hm+qCX0+UqbV2HvprWsYBziVfDKJgf0C0aHwHRa4tiXnqga6AdCpFVdvAmboBUbhoe5Zl1ldbdF8uzggu2LXJvkOdhwWrSbn5rQIBv2KCpvslNcMjDxRw4+OQHCrQGgAbbHKpuymvRqRvppdvMlh5L9M+7AdYPkvWZJj7LHi8eXneOEnNN3HOvDUztuG3olsWqi9gr4RSTKiYqgzPtPKUqUrzlDOKV+6vf75oKm4xPctvzYpjNhblPm0t6O/RRir/Ksah2SxAo5Y+3ncZkb+U6FsXy6F21H7fgIh/gkcM+jmmBMs0LNeHnDoOeLsRZO2kGGLAb775GEVwFBkZAi9xtSRT1V2FbE2QW6CIkvnc0iWvVU+B/nzrPeFF4BMFxjRk6yOL3Em/plCWpw9oLAPbgwFrCCdfHaki+mVIrQpVI4MLgsgCFni1g7cI64QPClI3c8HeVmxtXKIDLO39H0iPaiHUFY7ny+lm/oDELcaE=}
provider:
  win: azure
conda_forge_output_validation: true
